### ISSUE TITLE
Error in building: unexpected token when not ending a computed statement with ;

### ISSUE THREAD

**Issue by rster2002** [unlocomqx/svelte-reactive-preprocessor#2]
**What?**
If you do not end the computed statement with a ; the tool will throw stating there is an unexpected token. 

**How to reproduce**
```svelte
<script>
// Data
var a = 0;
var b = 0;

// Computed
$: output = a + b
</script>

<div>
    <input bind:value={a} type="number" />
    <input bind:value={b} type="number" />
    <p>{output}</p>
</div>
```

**Log**
```
ParseError: \src\views\Testing.svelte
Unexpected token (8:336)
 6:
 7: // Computed
 8: $: { let svrp_start = Date.now(); let svrp_exec = Math.random(); let start_state = eval("$$self.$capture_state && $$self.$capture_state()"); rpDsp('SvelteReactiveStart', {statement: "output = a + b", filename: "D:\\Github\\dndtools\\src\\views\\Testing.svelte", line: 7, id: "Zf8J"}, svrp_start, svrp_exec, start_state); output = a + b rpDsp('SvelteReactiveEnd', {statement: "output = a + b", filename: "D:\\Github\\dndtools\\src\\views\\Testing.svelte", line: 7, id: "Zf8J"}, svrp_start, svrp_exec, start_state, eval("$$self.$capture_state && $$self.$capture_state()")); }

                                                                                                               ^
 9:
10:  var rpGlobal = typeof window !== "undefined" ? window : global;
    at compileModule (D:\Github\dndtools\node_modules\nollup\lib\impl\NollupCompiler.js:115:19)
    at async compileModule (D:\Github\dndtools\node_modules\nollup\lib\impl\NollupCompiler.js:113:13)
    at async compileModule (D:\Github\dndtools\node_modules\nollup\lib\impl\NollupCompiler.js:113:13)
    at async compileInputTarget (D:\Github\dndtools\node_modules\nollup\lib\impl\NollupCompiler.js:137:5)
    at async Object.compile (D:\Github\dndtools\node_modules\nollup\lib\impl\NollupCompiler.js:208:31)
    at async generateImpl (D:\Github\dndtools\node_modules\nollup\lib\index.js:13:21)
```

**Comment by unlocomqx** [comment]
I added the semi-colon to fix the issue quickly. I will make the necessary checks to cover this case.
You can install version 0.6.1 from npm
`npm i -D svelte-reactive-preprocessor@0.6.1`

**Comment by rster2002** [comment]
Wow that was quick. Thanks 👍
