### ISSUE TITLE
svelte-reactive-preprocessor makes webpack crash on certain local code errors

### ISSUE THREAD

**Issue by maxlath** [unlocomqx/svelte-reactive-preprocessor#5]
When using `svelte-preprocess-sass` has a preprocessor to be passed to the webpack `svelte-loader`, making certain mistakes in the code makes the webpack watcher crash, example:

```
ERROR in ./some_component.svelte
Module build failed (from ./node_modules/svelte-loader/index.js):
SyntaxError: An error occurred in the svelte-reactive-preprocessor, make sure it's placed after the typescript preprocessor: Identifier 'someVariable' has already been declared (76:6)
    at Parser.pp$4.raise (node_modules/svelte-reactive-preprocessor/node_modules/acorn/dist/acorn.js:3462:15)
    at Parser.pp$3.declareName (node_modules/svelte-reactive-preprocessor/node_modules/acorn/dist/acorn.js:3538:28)
    at Parser.pp$7.checkLValSimple (node_modules/svelte-reactive-preprocessor/node_modules/acorn/dist/acorn.js:2138:50)
    at Parser.pp$7.checkLValPattern (node_modules/svelte-reactive-preprocessor/node_modules/acorn/dist/acorn.js:2180:12)
    at Parser.pp$8.parseVarId (node_modules/svelte-reactive-preprocessor/node_modules/acorn/dist/acorn.js:1315:10)
    at Parser.pp$8.parseVar (node_modules/svelte-reactive-preprocessor/node_modules/acorn/dist/acorn.js:1297:12)
    at Parser.pp$8.parseVarStatement (node_modules/svelte-reactive-preprocessor/node_modules/acorn/dist/acorn.js:1163:10)
    at Parser.pp$8.parseStatement (node_modules/svelte-reactive-preprocessor/node_modules/acorn/dist/acorn.js:911:19)
    at Parser.pp$8.parseTopLevel (node_modules/svelte-reactive-preprocessor/node_modules/acorn/dist/acorn.js:813:23)
    at Parser.parse (node_modules/svelte-reactive-preprocessor/node_modules/acorn/dist/acorn.js:585:17)

2022-06-27 14:17:16: webpack 5.69.0 compiled with 1 error in 453 ms
node:internal/validators:119
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.dirname (node:path:1276:5)
    at WatcherManager.watchFile (node_modules/watchpack/lib/getWatcherManager.js:30:26)
    at node_modules/watchpack/lib/watchpack.js:278:41
    at Object.exports.batch (node_modules/watchpack/lib/watchEventSource.js:326:3)
    at Watchpack.watch (node_modules/watchpack/lib/watchpack.js:276:20)
    at NodeWatchFileSystem.watch (node_modules/webpack/lib/node/NodeWatchFileSystem.js:107:16)
    at Watching.watch (node_modules/webpack/lib/Watching.js:325:48)
    at node_modules/webpack/lib/Watching.js:303:13 {
  code: 'ERR_INVALID_ARG_TYPE'
```

Note that in [our setup](https://github.com/inventaire/inventaire-client/blob/16e099bd41392501a9b1b9893326d16840f86091/bundle/rules/svelte.cjs) there is no typescript preprocessor.

As ESlint already gives a warning in the webpack watch logs for that kind of mistake, I guess simply catching the acorn error and ignoring it, possibly with a simple warning, could be an option?

Thanks in advance for any help

**Comment by unlocomqx** [comment]
I turned the error into a console.warn and then the preprocessor bails

`Version @0.8.2`

**Comment by maxlath** [comment]
it works, thanks!
